/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationIndexRouteImport } from './routes/reservation/index'
import { Route as OffresIndexRouteImport } from './routes/offres/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReservationTripIdRouteImport } from './routes/reservation/$tripId'
import { Route as OffresSlugRouteImport } from './routes/offres/$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminTripsRouteImport } from './routes/admin/trips'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminReservationsRouteImport } from './routes/admin/reservations'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGalerieRouteImport } from './routes/admin/galerie'
import { Route as AdminDestinationsRouteImport } from './routes/admin/destinations'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminOffresIndexRouteImport } from './routes/admin/offres/index'
import { Route as ReservationConfirmationRefRouteImport } from './routes/reservation/confirmation/$ref'
import { Route as AdminOffresNouveauRouteImport } from './routes/admin/offres/nouveau'
import { Route as AdminOffresIdRouteImport } from './routes/admin/offres/$id'
import { Route as AdminDestinationsDestinationIdRouteImport } from './routes/admin/destinations/$destinationId'
import { Route as AdminDestinationsDestinationIdOffresOfferIdRouteImport } from './routes/admin/destinations/$destinationId/offres/$offerId'
import { Route as AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRouteImport } from './routes/admin/destinations/$destinationId/offres/$offerId/sessions/$sessionId'

const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIndexRoute = ReservationIndexRouteImport.update({
  id: '/reservation/',
  path: '/reservation/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresIndexRoute = OffresIndexRouteImport.update({
  id: '/offres/',
  path: '/offres/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ReservationTripIdRoute = ReservationTripIdRouteImport.update({
  id: '/reservation/$tripId',
  path: '/reservation/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresSlugRoute = OffresSlugRouteImport.update({
  id: '/offres/$slug',
  path: '/offres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalerieRoute = AdminGalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDestinationsRoute = AdminDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOffresIndexRoute = AdminOffresIndexRouteImport.update({
  id: '/offres/',
  path: '/offres/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ReservationConfirmationRefRoute =
  ReservationConfirmationRefRouteImport.update({
    id: '/reservation/confirmation/$ref',
    path: '/reservation/confirmation/$ref',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOffresNouveauRoute = AdminOffresNouveauRouteImport.update({
  id: '/offres/nouveau',
  path: '/offres/nouveau',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOffresIdRoute = AdminOffresIdRouteImport.update({
  id: '/offres/$id',
  path: '/offres/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDestinationsDestinationIdRoute =
  AdminDestinationsDestinationIdRouteImport.update({
    id: '/$destinationId',
    path: '/$destinationId',
    getParentRoute: () => AdminDestinationsRoute,
  } as any)
const AdminDestinationsDestinationIdOffresOfferIdRoute =
  AdminDestinationsDestinationIdOffresOfferIdRouteImport.update({
    id: '/offres/$offerId',
    path: '/offres/$offerId',
    getParentRoute: () => AdminDestinationsDestinationIdRoute,
  } as any)
const AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRoute =
  AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRouteImport.update(
    {
      id: '/sessions/$sessionId',
      path: '/sessions/$sessionId',
      getParentRoute: () => AdminDestinationsDestinationIdOffresOfferIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/reservations': typeof ReservationsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/destinations': typeof AdminDestinationsRouteWithChildren
  '/admin/galerie': typeof AdminGalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/trips': typeof AdminTripsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/offres/$slug': typeof OffresSlugRoute
  '/reservation/$tripId': typeof ReservationTripIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/offres/': typeof OffresIndexRoute
  '/reservation/': typeof ReservationIndexRoute
  '/admin/destinations/$destinationId': typeof AdminDestinationsDestinationIdRouteWithChildren
  '/admin/offres/$id': typeof AdminOffresIdRoute
  '/admin/offres/nouveau': typeof AdminOffresNouveauRoute
  '/reservation/confirmation/$ref': typeof ReservationConfirmationRefRoute
  '/admin/offres/': typeof AdminOffresIndexRoute
  '/admin/destinations/$destinationId/offres/$offerId': typeof AdminDestinationsDestinationIdOffresOfferIdRouteWithChildren
  '/admin/destinations/$destinationId/offres/$offerId/sessions/$sessionId': typeof AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/reservations': typeof ReservationsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/destinations': typeof AdminDestinationsRouteWithChildren
  '/admin/galerie': typeof AdminGalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/trips': typeof AdminTripsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/offres/$slug': typeof OffresSlugRoute
  '/reservation/$tripId': typeof ReservationTripIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/offres': typeof OffresIndexRoute
  '/reservation': typeof ReservationIndexRoute
  '/admin/destinations/$destinationId': typeof AdminDestinationsDestinationIdRouteWithChildren
  '/admin/offres/$id': typeof AdminOffresIdRoute
  '/admin/offres/nouveau': typeof AdminOffresNouveauRoute
  '/reservation/confirmation/$ref': typeof ReservationConfirmationRefRoute
  '/admin/offres': typeof AdminOffresIndexRoute
  '/admin/destinations/$destinationId/offres/$offerId': typeof AdminDestinationsDestinationIdOffresOfferIdRouteWithChildren
  '/admin/destinations/$destinationId/offres/$offerId/sessions/$sessionId': typeof AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/reservations': typeof ReservationsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/destinations': typeof AdminDestinationsRouteWithChildren
  '/admin/galerie': typeof AdminGalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/trips': typeof AdminTripsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/offres/$slug': typeof OffresSlugRoute
  '/reservation/$tripId': typeof ReservationTripIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/offres/': typeof OffresIndexRoute
  '/reservation/': typeof ReservationIndexRoute
  '/admin/destinations/$destinationId': typeof AdminDestinationsDestinationIdRouteWithChildren
  '/admin/offres/$id': typeof AdminOffresIdRoute
  '/admin/offres/nouveau': typeof AdminOffresNouveauRoute
  '/reservation/confirmation/$ref': typeof ReservationConfirmationRefRoute
  '/admin/offres/': typeof AdminOffresIndexRoute
  '/admin/destinations/$destinationId/offres/$offerId': typeof AdminDestinationsDestinationIdOffresOfferIdRouteWithChildren
  '/admin/destinations/$destinationId/offres/$offerId/sessions/$sessionId': typeof AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/a-propos'
    | '/contact'
    | '/galerie'
    | '/reservations'
    | '/admin/blog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/destinations'
    | '/admin/galerie'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/reservations'
    | '/admin/sessions'
    | '/admin/trips'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/offres/$slug'
    | '/reservation/$tripId'
    | '/admin/'
    | '/blog/'
    | '/destinations/'
    | '/offres/'
    | '/reservation/'
    | '/admin/destinations/$destinationId'
    | '/admin/offres/$id'
    | '/admin/offres/nouveau'
    | '/reservation/confirmation/$ref'
    | '/admin/offres/'
    | '/admin/destinations/$destinationId/offres/$offerId'
    | '/admin/destinations/$destinationId/offres/$offerId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/galerie'
    | '/reservations'
    | '/admin/blog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/destinations'
    | '/admin/galerie'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/reservations'
    | '/admin/sessions'
    | '/admin/trips'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/offres/$slug'
    | '/reservation/$tripId'
    | '/admin'
    | '/blog'
    | '/destinations'
    | '/offres'
    | '/reservation'
    | '/admin/destinations/$destinationId'
    | '/admin/offres/$id'
    | '/admin/offres/nouveau'
    | '/reservation/confirmation/$ref'
    | '/admin/offres'
    | '/admin/destinations/$destinationId/offres/$offerId'
    | '/admin/destinations/$destinationId/offres/$offerId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/a-propos'
    | '/contact'
    | '/galerie'
    | '/reservations'
    | '/admin/blog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/destinations'
    | '/admin/galerie'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/reservations'
    | '/admin/sessions'
    | '/admin/trips'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/offres/$slug'
    | '/reservation/$tripId'
    | '/admin/'
    | '/blog/'
    | '/destinations/'
    | '/offres/'
    | '/reservation/'
    | '/admin/destinations/$destinationId'
    | '/admin/offres/$id'
    | '/admin/offres/nouveau'
    | '/reservation/confirmation/$ref'
    | '/admin/offres/'
    | '/admin/destinations/$destinationId/offres/$offerId'
    | '/admin/destinations/$destinationId/offres/$offerId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  GalerieRoute: typeof GalerieRoute
  ReservationsRoute: typeof ReservationsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  OffresSlugRoute: typeof OffresSlugRoute
  ReservationTripIdRoute: typeof ReservationTripIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  OffresIndexRoute: typeof OffresIndexRoute
  ReservationIndexRoute: typeof ReservationIndexRoute
  ReservationConfirmationRefRoute: typeof ReservationConfirmationRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/': {
      id: '/reservation/'
      path: '/reservation'
      fullPath: '/reservation/'
      preLoaderRoute: typeof ReservationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/': {
      id: '/offres/'
      path: '/offres'
      fullPath: '/offres/'
      preLoaderRoute: typeof OffresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/reservation/$tripId': {
      id: '/reservation/$tripId'
      path: '/reservation/$tripId'
      fullPath: '/reservation/$tripId'
      preLoaderRoute: typeof ReservationTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/$slug': {
      id: '/offres/$slug'
      path: '/offres/$slug'
      fullPath: '/offres/$slug'
      preLoaderRoute: typeof OffresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/galerie': {
      id: '/admin/galerie'
      path: '/galerie'
      fullPath: '/admin/galerie'
      preLoaderRoute: typeof AdminGalerieRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/destinations': {
      id: '/admin/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/offres/': {
      id: '/admin/offres/'
      path: '/offres'
      fullPath: '/admin/offres/'
      preLoaderRoute: typeof AdminOffresIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/reservation/confirmation/$ref': {
      id: '/reservation/confirmation/$ref'
      path: '/reservation/confirmation/$ref'
      fullPath: '/reservation/confirmation/$ref'
      preLoaderRoute: typeof ReservationConfirmationRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offres/nouveau': {
      id: '/admin/offres/nouveau'
      path: '/offres/nouveau'
      fullPath: '/admin/offres/nouveau'
      preLoaderRoute: typeof AdminOffresNouveauRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/offres/$id': {
      id: '/admin/offres/$id'
      path: '/offres/$id'
      fullPath: '/admin/offres/$id'
      preLoaderRoute: typeof AdminOffresIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/destinations/$destinationId': {
      id: '/admin/destinations/$destinationId'
      path: '/$destinationId'
      fullPath: '/admin/destinations/$destinationId'
      preLoaderRoute: typeof AdminDestinationsDestinationIdRouteImport
      parentRoute: typeof AdminDestinationsRoute
    }
    '/admin/destinations/$destinationId/offres/$offerId': {
      id: '/admin/destinations/$destinationId/offres/$offerId'
      path: '/offres/$offerId'
      fullPath: '/admin/destinations/$destinationId/offres/$offerId'
      preLoaderRoute: typeof AdminDestinationsDestinationIdOffresOfferIdRouteImport
      parentRoute: typeof AdminDestinationsDestinationIdRoute
    }
    '/admin/destinations/$destinationId/offres/$offerId/sessions/$sessionId': {
      id: '/admin/destinations/$destinationId/offres/$offerId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/admin/destinations/$destinationId/offres/$offerId/sessions/$sessionId'
      preLoaderRoute: typeof AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRouteImport
      parentRoute: typeof AdminDestinationsDestinationIdOffresOfferIdRoute
    }
  }
}

interface AdminDestinationsDestinationIdOffresOfferIdRouteChildren {
  AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRoute: typeof AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRoute
}

const AdminDestinationsDestinationIdOffresOfferIdRouteChildren: AdminDestinationsDestinationIdOffresOfferIdRouteChildren =
  {
    AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRoute:
      AdminDestinationsDestinationIdOffresOfferIdSessionsSessionIdRoute,
  }

const AdminDestinationsDestinationIdOffresOfferIdRouteWithChildren =
  AdminDestinationsDestinationIdOffresOfferIdRoute._addFileChildren(
    AdminDestinationsDestinationIdOffresOfferIdRouteChildren,
  )

interface AdminDestinationsDestinationIdRouteChildren {
  AdminDestinationsDestinationIdOffresOfferIdRoute: typeof AdminDestinationsDestinationIdOffresOfferIdRouteWithChildren
}

const AdminDestinationsDestinationIdRouteChildren: AdminDestinationsDestinationIdRouteChildren =
  {
    AdminDestinationsDestinationIdOffresOfferIdRoute:
      AdminDestinationsDestinationIdOffresOfferIdRouteWithChildren,
  }

const AdminDestinationsDestinationIdRouteWithChildren =
  AdminDestinationsDestinationIdRoute._addFileChildren(
    AdminDestinationsDestinationIdRouteChildren,
  )

interface AdminDestinationsRouteChildren {
  AdminDestinationsDestinationIdRoute: typeof AdminDestinationsDestinationIdRouteWithChildren
}

const AdminDestinationsRouteChildren: AdminDestinationsRouteChildren = {
  AdminDestinationsDestinationIdRoute:
    AdminDestinationsDestinationIdRouteWithChildren,
}

const AdminDestinationsRouteWithChildren =
  AdminDestinationsRoute._addFileChildren(AdminDestinationsRouteChildren)

interface AdminRouteRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDestinationsRoute: typeof AdminDestinationsRouteWithChildren
  AdminGalerieRoute: typeof AdminGalerieRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminTripsRoute: typeof AdminTripsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOffresIdRoute: typeof AdminOffresIdRoute
  AdminOffresNouveauRoute: typeof AdminOffresNouveauRoute
  AdminOffresIndexRoute: typeof AdminOffresIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDestinationsRoute: AdminDestinationsRouteWithChildren,
  AdminGalerieRoute: AdminGalerieRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminTripsRoute: AdminTripsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOffresIdRoute: AdminOffresIdRoute,
  AdminOffresNouveauRoute: AdminOffresNouveauRoute,
  AdminOffresIndexRoute: AdminOffresIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  GalerieRoute: GalerieRoute,
  ReservationsRoute: ReservationsRoute,
  BlogSlugRoute: BlogSlugRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  OffresSlugRoute: OffresSlugRoute,
  ReservationTripIdRoute: ReservationTripIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  OffresIndexRoute: OffresIndexRoute,
  ReservationIndexRoute: ReservationIndexRoute,
  ReservationConfirmationRefRoute: ReservationConfirmationRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
